
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// Single env source: secrets live in .env.local (Next.js + Prisma share it).
// dotenv/config only loads `.env`, so load .env.local explicitly here.
import { config } from "dotenv";
config({ path: ".env.local" });
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    url: env("DATABASE_URL"),
  },
});
