import { z } from "zod";
import type { AgentDefinition } from "./types";
import { CuratorInputSchema, CuratorOutputSchema } from "./opportunityCurator";

/**
 * 12 ürün rolü + Opportunity Curator skill'i — DEKLARATİF registry (ADR-027).
 *
 * Envanter kuralı (07-PHASE2-PLAN §1): hiçbir rol EKSİK değildir; her tanım
 * MEVCUT servise adapter ile bağlanır (adapters.ts). Bu dosya yalnız veridir:
 * prompt gövdesi, secret, çalıştırılabilir fonksiyon YOK. Ana navigasyonda
 * GÖSTERİLMEZ — arka plan altyapısıdır.
 *
 * Şema notu: servislerin zengin özet dönüşleri `.passthrough()` ile korunur;
 * anahtar alanlar typed. Şema sıkılaştırma rol bazında 2B–2E'de derinleşir.
 */

const handleInput = z.object({ accountHandle: z.string().min(1) });

const summaryOutput = z.object({}).passthrough();

export const AGENT_DEFINITIONS: AgentDefinition[] = [
  {
    id: "cem-orchestrator",
    version: "1.0.0",
    policyVersion: "2A",
    displayName: "Cem Orchestrator",
    purpose: "Günlük üretim zinciri: keşif → madencilik → taslak (mevcut pipelineService).",
    triggers: ["cron:generate-morning", "cron:daily backfill", "ui:operator-scan-now"],
    adapterId: "pipeline-daily-run",
    executionMode: "hybrid",
    inputSchema: handleInput.extend({ deadlineMs: z.number().int().positive().optional() }),
    outputSchema: summaryOutput,
    allowedCapabilities: ["db:read", "db:write:queue", "llm:generate", "memory:read", "net:social_sources"],
    preset: "cemos-writer",
    budgetClass: "essential",
    timeoutMs: 240_000,
    retry: { maxAttempts: 0 },
    fallback: { kind: "none" },
    memoryReadScopes: ["identity", "account", "style", "episodic", "negative"],
    memoryWriteScopes: [],
    provenance: "self_judge",
    tracePolicy: "always",
    evalFixtureIds: ["orchestrator-basic"],
    status: "enabled",
  },
  {
    id: "trend-scout",
    version: "1.0.0",
    policyVersion: "2A",
    displayName: "Trend Scout",
    purpose: "Kaynak keşfi + tekrar eden konu sinyali (discoveryService + trend-aggregator).",
    triggers: ["cron:daily", "ui:kesif"],
    adapterId: "trend-scout-compose",
    executionMode: "hybrid",
    inputSchema: handleInput,
    outputSchema: summaryOutput,
    allowedCapabilities: ["db:read", "llm:generate", "net:social_sources"],
    preset: "cemos-budget-batch",
    budgetClass: "background",
    timeoutMs: 120_000,
    retry: { maxAttempts: 1 },
    fallback: { kind: "deterministic", note: "LLM ön-filtre kapalıysa ham keşif sonuçları döner." },
    memoryReadScopes: ["account"],
    memoryWriteScopes: [],
    provenance: "external",
    tracePolicy: "on_llm",
    evalFixtureIds: ["trend-scout-basic"],
    status: "enabled",
  },
  {
    id: "account-strategist",
    version: "1.0.0",
    policyVersion: "2A",
    displayName: "Account Strategist",
    purpose: "İçerik-hesap uyum kararı (agents/router.routeItem + persona profilleri).",
    triggers: ["pipeline:news-fallback", "pipeline:routing"],
    adapterId: "router-route-item",
    executionMode: "llm",
    inputSchema: z.object({ text: z.string().min(1).max(20_000) }),
    outputSchema: z
      .object({ best: z.string().nullable(), usedLlm: z.boolean() })
      .passthrough(),
    allowedCapabilities: ["llm:generate", "memory:read"],
    preset: "cemos-fast-extract",
    budgetClass: "background",
    timeoutMs: 30_000,
    retry: { maxAttempts: 1 },
    fallback: { kind: "deterministic", note: "LLM düşerse fail-open nötr uyum (mevcut davranış)." },
    memoryReadScopes: ["identity", "account"],
    memoryWriteScopes: [],
    provenance: "self_judge",
    tracePolicy: "on_llm",
    evalFixtureIds: ["strategist-basic"],
    status: "enabled",
  },
  {
    id: "content-creator",
    version: "1.0.0",
    policyVersion: "2A",
    displayName: "Content Creator",
    purpose: "Çoklu-aday taslak üretimi (ai/draft-pipeline.runDraftPipeline; writer=cemos-writer).",
    triggers: ["pipeline:draft", "handoff:generate"],
    adapterId: "draft-pipeline-run",
    executionMode: "llm",
    inputSchema: z.object({
      accountHandle: z.string().min(1),
      sourceText: z.string().min(1).max(40_000),
      sourceType: z.string().optional(),
    }),
    outputSchema: summaryOutput,
    allowedCapabilities: ["db:read", "llm:generate", "memory:read"],
    preset: "cemos-writer",
    budgetClass: "essential",
    timeoutMs: 180_000,
    retry: { maxAttempts: 0 },
    fallback: { kind: "none" },
    memoryReadScopes: ["identity", "account", "style", "episodic", "negative"],
    memoryWriteScopes: [],
    provenance: "self_judge",
    tracePolicy: "always",
    evalFixtureIds: ["creator-basic"],
    status: "enabled",
  },
  {
    id: "viral-editor",
    version: "1.0.0",
    policyVersion: "2A",
    displayName: "Viral Editor",
    purpose: "Aday sıralama + kalite skoru (draft-pipeline judge / scorer.scoreDraft).",
    triggers: ["pipeline:judge"],
    adapterId: "scorer-score-draft",
    executionMode: "hybrid",
    inputSchema: z.object({
      accountHandle: z.string().min(1),
      content: z.string().min(1).max(20_000),
    }),
    outputSchema: summaryOutput,
    allowedCapabilities: ["llm:generate"],
    preset: "cemos-final-judge",
    budgetClass: "background",
    timeoutMs: 60_000,
    retry: { maxAttempts: 1 },
    fallback: { kind: "deterministic", note: "scoreDraftFallback deterministik skorlar." },
    memoryReadScopes: ["account", "negative"],
    memoryWriteScopes: [],
    provenance: "self_judge",
    tracePolicy: "on_llm",
    evalFixtureIds: ["viral-editor-basic"],
    status: "enabled",
  },
  {
    id: "brand-guardian",
    version: "1.0.0",
    policyVersion: "2A",
    displayName: "Brand Guardian",
    purpose: "Marka vetosu: council persona/risk lensleri + deterministik readiness kapısı.",
    triggers: ["pipeline:gate", "publish:readiness"],
    adapterId: "council-deliberate",
    executionMode: "hybrid",
    inputSchema: z.object({
      text: z.string().min(1).max(20_000),
      accountHandle: z.string().min(1),
    }),
    outputSchema: summaryOutput,
    allowedCapabilities: ["llm:generate", "memory:read"],
    preset: "cemos-fast-extract",
    budgetClass: "background",
    timeoutMs: 60_000,
    retry: { maxAttempts: 1 },
    fallback: { kind: "deterministic", note: "Lens düşerse nötr default (fail-open, mevcut davranış); veto readiness'te." },
    memoryReadScopes: ["identity", "account", "negative"],
    memoryWriteScopes: [],
    provenance: "self_judge",
    tracePolicy: "on_llm",
    evalFixtureIds: ["guardian-basic"],
    status: "enabled",
  },
  {
    id: "fact-checker",
    version: "1.0.0",
    policyVersion: "2A",
    displayName: "Fact Checker",
    purpose: "Site/kanıt doğrulama (verifyWebsite; karar KOD, LLM değil).",
    triggers: ["reels:evidence-gate", "toolbox:verify"],
    adapterId: "verify-website",
    executionMode: "deterministic",
    inputSchema: z.object({ url: z.string().url() }),
    outputSchema: summaryOutput,
    allowedCapabilities: ["db:read", "net:verify_website"],
    preset: null,
    budgetClass: null,
    timeoutMs: 45_000,
    retry: { maxAttempts: 1 },
    fallback: { kind: "none" },
    memoryReadScopes: [],
    memoryWriteScopes: [],
    provenance: "external",
    tracePolicy: "always",
    evalFixtureIds: ["fact-checker-basic"],
    status: "enabled",
  },
  {
    id: "originality-critic",
    version: "1.0.0",
    policyVersion: "2A",
    displayName: "Originality Critic",
    purpose: "Yakın-kopya tespiti (textSimilarity.isNearDuplicate — deterministik).",
    triggers: ["pipeline:dedup"],
    adapterId: "near-duplicate-check",
    executionMode: "deterministic",
    inputSchema: z.object({
      text: z.string().min(1).max(20_000),
      corpus: z.array(z.string()).max(500).default([]),
    }),
    outputSchema: z.object({ nearDuplicate: z.boolean(), matchedIndex: z.number().int().nullable() }),
    allowedCapabilities: ["db:read"],
    preset: null,
    budgetClass: null,
    timeoutMs: 10_000,
    retry: { maxAttempts: 0 },
    fallback: { kind: "none" },
    memoryReadScopes: ["episodic"],
    memoryWriteScopes: [],
    provenance: "self_judge",
    tracePolicy: "on_llm",
    evalFixtureIds: ["originality-basic"],
    status: "enabled",
  },
  {
    id: "competitor-analyst",
    version: "1.0.0",
    policyVersion: "2A",
    displayName: "Competitor Analyst",
    purpose: "IG/YouTube rakip senkron + outlier (igCompetitorService / youtube outlier; LLM-siz).",
    triggers: ["cron:daily", "ui:rakip-radari"],
    adapterId: "competitor-sync",
    executionMode: "deterministic",
    inputSchema: z.object({ platform: z.enum(["instagram", "youtube"]) }),
    outputSchema: summaryOutput,
    allowedCapabilities: ["db:read", "net:meta_graph", "net:youtube"],
    preset: null,
    budgetClass: null,
    timeoutMs: 120_000,
    retry: { maxAttempts: 0 },
    fallback: { kind: "none" },
    memoryReadScopes: [],
    memoryWriteScopes: [],
    provenance: "external",
    tracePolicy: "on_llm",
    evalFixtureIds: ["competitor-basic"],
    status: "enabled",
  },
  {
    id: "reels-planner",
    version: "1.0.0",
    policyVersion: "2A",
    displayName: "Reels Planner",
    purpose: "Reel dossier üretimi + aylık plan montajı (dossier-generator / plan-assembler).",
    triggers: ["ui:takvim-plan", "ui:dossier"],
    adapterId: "reels-plan-assemble",
    executionMode: "hybrid",
    inputSchema: z.object({}).passthrough(),
    outputSchema: summaryOutput,
    allowedCapabilities: ["db:read", "db:write:plan", "llm:generate", "net:verify_website"],
    preset: "cemos-writer",
    budgetClass: "essential",
    timeoutMs: 240_000,
    retry: { maxAttempts: 0 },
    fallback: { kind: "deterministic", note: "Aylık plan montajı saf/deterministik; yalnız dossier LLM." },
    memoryReadScopes: ["style", "series"],
    memoryWriteScopes: [],
    provenance: "self_judge",
    tracePolicy: "always",
    evalFixtureIds: ["reels-planner-basic"],
    status: "enabled",
  },
  {
    id: "performance-learner",
    version: "1.0.0",
    policyVersion: "2A",
    displayName: "Performance Learner",
    purpose: "Yayın↔metrik eşleme + pattern ağırlığı + feedback (engagementLearningService).",
    triggers: ["cron:learn", "ui:feedback"],
    adapterId: "engagement-sync",
    executionMode: "deterministic",
    inputSchema: handleInput,
    outputSchema: summaryOutput,
    allowedCapabilities: ["db:read", "memory:write:episodic", "net:social_sources"],
    preset: null,
    budgetClass: null,
    timeoutMs: 120_000,
    retry: { maxAttempts: 0 },
    fallback: { kind: "none" },
    memoryReadScopes: ["performance", "episodic"],
    memoryWriteScopes: ["episodic", "performance"],
    provenance: "own_metric",
    tracePolicy: "on_llm",
    evalFixtureIds: ["learner-basic"],
    status: "enabled",
  },
  {
    id: "knowledge-curator",
    version: "1.0.0",
    policyVersion: "2A",
    displayName: "Knowledge Curator",
    purpose: "Learn pipeline ilerletme + hafıza konsolidasyonu (advanceJob / runMemoryConsolidation).",
    triggers: ["cron:learn", "ui:ogrenme"],
    adapterId: "knowledge-advance",
    executionMode: "hybrid",
    inputSchema: z.object({
      action: z.enum(["advance_job", "consolidate_memory"]),
      jobId: z.string().optional(),
      handles: z.array(z.string()).optional(),
      deadlineMs: z.number().int().positive().optional(),
    }),
    outputSchema: summaryOutput,
    allowedCapabilities: ["db:read", "db:write:learn", "llm:generate", "memory:read", "memory:write:identity"],
    preset: "cemos-memory",
    budgetClass: "background",
    timeoutMs: 240_000,
    retry: { maxAttempts: 0 },
    fallback: { kind: "none" },
    memoryReadScopes: ["knowledge", "episodic"],
    memoryWriteScopes: ["knowledge", "identity"],
    provenance: "self_judge",
    tracePolicy: "always",
    evalFixtureIds: ["curator-knowledge-basic"],
    status: "enabled",
  },
  {
    id: "opportunity-curator",
    version: "1.0.0",
    policyVersion: "2A",
    displayName: "Opportunity Curator",
    purpose: "Fırsat kürasyonu: deterministik sıralama (aktif) + typed LLM yolu (kredi onayına kadar kapalı).",
    triggers: ["ui:firsatlar"],
    adapterId: "opportunity-curate",
    executionMode: "hybrid",
    inputSchema: CuratorInputSchema,
    outputSchema: CuratorOutputSchema,
    allowedCapabilities: ["llm:generate"],
    preset: "cemos-research",
    budgetClass: "background",
    timeoutMs: 45_000,
    retry: { maxAttempts: 0 },
    fallback: { kind: "deterministic", note: "opportunityCuration deterministik sıralaması güvenli fallback." },
    memoryReadScopes: ["account"],
    memoryWriteScopes: [],
    provenance: "self_judge",
    tracePolicy: "always",
    evalFixtureIds: ["curation-basic", "curation-insufficient-sample", "curation-source-cap"],
    status: "enabled",
  },
];

/** X API doğrudan yayını registry'de temsil edilmez — publish yolunun tek sahibi publishAttemptService (ADR-025). */
export const AGENT_ROLE_IDS = AGENT_DEFINITIONS.map((d) => d.id);
